### ISSUE TITLE
Run ThriftConsumer main failed  in Debug mode

### ISSUE THREAD

**Issue by liangyanfeng** [Meituan-Dianping/octo-rpc#1]
**Console ouput:**

2019/03/13 16:33:39.488 main [WARN] TraceFactory (TraceFactory.java:40) No impl of InvokeTrace, will not do performance trace.
2019/03/13 16:33:39.713 main [INFO] AbstractHttpServer (AbstractHttpServer.java:90) Start HttpServer bind 0.0.0.0/0.0.0.0:5081
2019/03/13 16:33:39.856 main [INFO] AbstractClient (AbstractClient.java:147) Succeed connect to server /127.0.0.1:9001 from com.meituan.dorado.transport.netty.NettyClient, channel is [id: 0x883b27b9, L:/127.0.0.1:56767 - R:/127.0.0.1:9001]
Hello OCTO
2019/03/13 16:33:40.047 NettyClientWorkerGroup-4-1 [ERROR] NettyChannel (NettyChannel.java:62) Failed to send message[Request(com.meituan.dorado.demo.thrift.api.HelloService)] to /127.0.0.1:9001.
io.netty.handler.codec.EncoderException: com.meituan.dorado.common.exception.ProtocolException: Thrift serialize request: classcom.meituan.dorado.demo.thrift.api.HelloService$toString_args load failed.
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.meituan.dorado.common.exception.ProtocolException: Thrift serialize request: classcom.meituan.dorado.demo.thrift.api.HelloService$toString_args load failed.
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.getClazzInstance(ThriftIDLSerializer.java:360) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.doSerializeRequest(ThriftIDLSerializer.java:238) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.serialize(ThriftIDLSerializer.java:223) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftCodecSerializer.encodeThrift(ThriftCodecSerializer.java:114) ~[classes/:?]
	at com.meituan.dorado.codec.octo.OctoCodec.encodeThrift(OctoCodec.java:403) ~[classes/:?]
	at com.meituan.dorado.codec.octo.OctoCodec.encode(OctoCodec.java:82) ~[classes/:?]
	at com.meituan.dorado.transport.netty.NettyCodec.encode(NettyCodec.java:65) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.meituan.dorado.demo.thrift.api.HelloService$toString_args
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:993) ~[commons-lang3-3.7.jar:3.7]
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1027) ~[commons-lang3-3.7.jar:3.7]
	at com.meituan.dorado.common.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:26) ~[classes/:?]
	at com.meituan.dorado.common.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:30) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.getClazzInstance(ThriftIDLSerializer.java:357) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.doSerializeRequest(ThriftIDLSerializer.java:238) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftIDLSerializer.serialize(ThriftIDLSerializer.java:223) ~[classes/:?]
	at com.meituan.dorado.serialize.thrift.ThriftCodecSerializer.encodeThrift(ThriftCodecSerializer.java:114) ~[classes/:?]
	at com.meituan.dorado.codec.octo.OctoCodec.encodeThrift(OctoCodec.java:403) ~[classes/:?]
	at com.meituan.dorado.codec.octo.OctoCodec.encode(OctoCodec.java:82) ~[classes/:?]
	at com.meituan.dorado.transport.netty.NettyCodec.encode(NettyCodec.java:65) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 19 more
2019/03/13 16:33:51.599 main [INFO] AbstractClient (AbstractClient.java:188) Closing com.meituan.dorado.transport.netty.NettyClient connect to server localhost/127.0.0.1:9001
2019/03/13 16:33:51.600 main [INFO] AbstractClient (AbstractClient.java:161) Disconnecting to server localhost/127.0.0.1:9001
2019/03/13 16:33:51.600 main [INFO] NettyChannel (NettyChannel.java:82) Closing netty channel [id: 0x883b27b9, L:/127.0.0.1:56767 - R:/127.0.0.1:9001]
2019/03/13 16:33:51.603 main [INFO] AbstractHttpServer (AbstractHttpServer.java:56) Closing HttpServer bind 0.0.0.0/0.0.0.0:5081
2019/03/13 16:33:51.604 main [INFO] ServiceInvocationRepository (ServiceInvocationRepository.java:118) Stop HashedWheelTimer
Disconnected from the target VM, address: '127.0.0.1:56762', transport: 'socket'

Process finished with exit code 0

**Comment by YangruiEmma** [comment]
请问是不是debug了，这里使用的是JDK的动态代理，会代理toString，正常运行不会有该问题。感谢反馈，我们会对此做优化；）

**Comment by YangruiEmma** [comment]
@liangyanfeng 您提的问题已修改，可以拉下最新的代码进行测试，感谢反馈~ 这个issue可以关了吗？

**Comment by liangyanfeng** [comment]
Ok, 问题已经修复，非常感谢！
